### PR TITLE
Bundle the highlight.js library

### PR DESCRIPTION
**Pull request by mortenpi**
Julia 0.6 related updates are not available in the latest release yet, so we can't use the CDN version for the time being.

This includes the highlight.js v9.11.0+ version build by hand from the highlight.js commit `35f2ff935e9d45c50feab6ee7538382a0f2412f6`. This includes the Julia 0.6 syntax updates.

cc @ararslan. It turns out that installing Node wasn't such a hassle after all on Ubuntu, so I think I've managed to build it for us. Could you give this branch a quick spin by any chance to make sure the highlighting works properly?

### CODE REVIEW

**Comment by mortenpi** [comment]
There's also a build of Documenter's docs based off this branch: http://mortenpi.eu/Documenter.jl/bundle-highlightjs-deploy/

**Comment by ararslan** [comment]
Comparing [`deploydocs` for this build](http://mortenpi.eu/Documenter.jl/bundle-highlightjs-deploy/lib/public.html#Documenter.deploydocs) against [`deploydocs` on the master build](https://juliadocs.github.io/Documenter.jl/latest/lib/public.html#Documenter.deploydocs), it seems that highlighting isn't working properly. Note that `using` isn't being highlighted at all in the second code block in the docstring.

**Comment by mortenpi** [comment]
I had a small bug, I didn't actually copy over the javascript file. The build should be fixed now, but you might have to force-refresh.

**Comment by ararslan** [comment]
Okay, tried it out locally, but I'm getting this error (not sure if related, maybe I'm not doing this right):
```
[15:49:37] alex:TestHighlight.jl $ julia -e 'include("src/TestHighlight.jl"); include("../Documenter.jl/src/Documenter.jl"); include("docs/make.jl")'
ERROR: LoadError: MethodError: no method matching order(::Type{Documenter.Builder.CrossReferences})
The applicable method may be too new: running in world age 21950, while current world is 22469.
Closest candidates are:
  order(::Type{Documenter.Builder.CrossReferences}) at /Users/alex/Projects/Documenter.jl/src/Builder.jl:68 (method too new to be called from this world context.)
  order(!Matched::Type{Documenter.Builder.SetupBuildDirectory}) at /Users/alex/Projects/Documenter.jl/src/Builder.jl:66 (method too new to be called from this world context.)
  order(!Matched::Type{Documenter.Builder.ExpandTemplates}) at /Users/alex/Projects/Documenter.jl/src/Builder.jl:67 (method too new to be called from this world context.)
  ...
Stacktrace:
 [1] lt(::Base.Order.By{Documenter.Selectors.#order}, ::DataType, ::DataType) at ./ordering.jl:47
 [2] sort!(::Array{Union{DataType, UnionAll},1}, ::Int64, ::Int64, ::Base.Sort.InsertionSortAlg, ::Base.Order.By{Documenter.Selectors.#order}) at ./sort.jl:252
 [3] sort!(::Array{Union{DataType, UnionAll},1}, ::Int64, ::Int64, ::Base.Sort.MergeSortAlg, ::Base.Order.By{Documenter.Selectors.#order}, ::Array{Union{DataType, UnionAll},1}) at ./sort.jl:341
 [4] sort!(::Array{Union{DataType, UnionAll},1}, ::Base.Sort.MergeSortAlg, ::Base.Order.By{Documenter.Selectors.#order}) at ./sort.jl:435
 [5] #sort!#7(::Base.Sort.MergeSortAlg, ::Function, ::Function, ::Bool, ::Base.Order.ForwardOrdering, ::Function, ::Array{Union{DataType, UnionAll},1}) at ./sort.jl:494
 [6] (::Base.#kw##sort!)(::Array{Any,1}, ::Base.#sort!, ::Array{Union{DataType, UnionAll},1}) at ./<missing>:0
 [7] #sort#8(::Array{Any,1}, ::Function, ::Array{Union{DataType, UnionAll},1}) at ./sort.jl:541
 [8] (::Base.#kw##sort)(::Array{Any,1}, ::Base.#sort, ::Array{Union{DataType, UnionAll},1}) at ./<missing>:0
 [9] dispatch(...) at /Users/alex/Projects/Documenter.jl/src/Selectors.jl:164
 [10] cd(::Documenter.##2#3{Documenter.Documents.Document}, ::String) at ./file.jl:70
 [11] #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at /Users/alex/Projects/Documenter.jl/src/Documenter.jl:198
 [12] (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at ./<missing>:0
 [13] include_from_node1(::String) at ./loading.jl:539
 [14] include(::String) at ./sysimg.jl:14
while loading /Users/alex/Projects/TestHighlight.jl/docs/make.jl, in expression starting on line 3
```
where the contents of make.jl is
```julia
using TestHighlight, Documenter

makedocs(
    modules = [TestHighlight],
    clean = false,
    format = :html,
    sitename = "TestHighlight.jl",
    authors = "Alex",
    pages = [
        "Home" => "index.md",
    ],
)
```

**Comment by mortenpi** [comment]
I think that's unrelated to this PR, but it's interesting.. you're running the latest master I presume? It looks like something that was introduced in Base at some point.

**Comment by mortenpi** [comment]
Or it could be just that you're overriding the `Documenter` module.
```julia
include("src/TestHighlight.jl")
include("../Documenter.jl/src/Documenter.jl")
include("docs/make.jl")
```
Couldn't you drop the `include("../Documenter.jl/src/Documenter.jl")`?

**Comment by ararslan** [comment]
I could, this is just the lazy way in that it avoids using `Pkg` at all. I tried with Julia 0.5 and things work fine.

The good news is that the Julia highlighting is accurate and has all of the 0.6 definitions I added to highlight.js. The bad news is that `jldoctest` still doesn't have highlighting.

**Comment by mortenpi** [comment]
> this is just the lazy way

Ah, I see, they're not in `Pkg.dir()`. Maybe `JULIA_LOAD_PATH` would help here.

In any case, I think the doctest stuff is now fixed and highlight.js' new alias seems to be working fine. The only thing remaining would be to decide whether we'd like to change the name of the alias (https://github.com/JuliaDocs/Documenter.jl/issues/465#issuecomment-298140680) and updating highlight.js before merging this.

I also think that these commits would qualify as a bugfix, so I could do a patch release with this once it's merged to get the doctests fixed in the manual.

**Comment by mortenpi** [comment]
Bundled highligh.js with the `julia-repl` implementation (built it from my fork). Example output: http://mortenpi.eu/Documenter.jl/bundle-highlightjs-deploy/highlight-examples.html

**Comment by mortenpi** [comment]
I think I'll merge, backport and tag this so that we'd get doctests and the CDN stuff fixed in base. We can always change things later, and AFAICT this shouldn't break anything (unless someone is applying custom styling on `language-jldoctest` classes).

**Pull request merged**
