### PR TITLE
Fix multiline display equations in HTML

### PR DESCRIPTION
**Pull request by odow**
This came from the JuMP docs: https://github.com/jump-dev/JuMP.jl/pull/2447#discussion_r569597250. We have some multiline display equations with `\n` in them (e.g., to format arrays).

Follows: https://github.com/JuliaDocs/Documenter.jl/pull/1426

Seems like it also fixes https://github.com/JuliaDocs/Documenter.jl/issues/1387

Is there a better way of testing this? I just followed #1426.

### CODE REVIEW

**Comment by odow** [comment]
Ideas on the failing `docs/pdf/make.jl` build?

**Comment by mortenpi** [comment]
> Ideas on the failing docs/pdf/make.jl build?

I think you end up with literal `\` and `n` characters in the TeX code in the updated examples now, since they are `raw""` strings?

**Comment by odow** [comment]
Oh, thanks. I though I recalled `raw"` being cleverer than that with `\n`.

**Comment by odow** [comment]
Tests passing.

**Review by mortenpi — APPROVED** [review]
I expanded the tests a bit, but otherwise LGTM! Thanks @odow!

**Comment by odow** [comment]
Thanks Morten.

**Pull request merged**
