### PR TITLE
deploydocs: check that `julia` is a string, repo matches repo_slug

### PR DESCRIPTION
**Pull request by timholy**
I spent some time debugging a puzzling failure-to-deploy, before finally noticing that in my `make.jl` I had specified `julia = 0.5` rather than `julia = "0.5"`.

### CODE REVIEW

**Comment by timholy** [comment]
I should note that it wasn't clear to me whether the repo test should be a warning or an error; I decided on a warning, but an error would obviously be much easier to test for.

**Comment by MichaelHatherly** [comment]
Thanks. I'd be fine with both being `error`s, rather than just `warn`ing the user about the mismatch.

**Comment by timholy** [comment]
Done.

**Comment by MichaelHatherly** [comment]
Thanks.

**Pull request merged**
