### PR TITLE
breaking changes: Woodpecker CI updates and deprecations

### PR DESCRIPTION
**Pull request by uncomfyhalomacro**
- Woodpecker CI is no longer backwards compatible with Drone due to lots of deprecated syntax and env vars

https://woodpecker-ci.org/docs/next/migrations#next-200

### CODE REVIEW

**Comment by uncomfyhalomacro** [comment]
I will fix this over the weekend. :)

**Comment by mortenpi** [comment]
So if I understand correctly, this will now only work in pipelines running on Woodpecker 2? And it would start failing on any Woodpecker 1 installations?

**Comment by uncomfyhalomacro** [comment]
> So if I understand correctly, this will now only work in pipelines running on Woodpecker 2? And it would start failing on any Woodpecker 1 installations?

Yes and No. The previous PR i made before was pre-1.x, i think specifically 0.15.x (?). The latest stable release version 1.0.0 starts to deprecate but not remove some old environmental variables e.g. `CI_BUILD*` -> `CI_PIPELINE*`. In the 2.0.0 `next` branch which is not released yet, those deprecated becomes "removed" so those env vars won't exist anymore.

**Comment by mortenpi** [comment]
Ah, right-right. But this would fail for anyone using Woodpecker 0.15? And this is theoretically possible, since it can be self-hosted.. actually.. I am a little bit confused -- does Woodpecker even offer a central service? Or is it always self-hosted?

I feel that to do this properly, we would need to version guard things, if that's something that can be done. I.e. use different sets of environment variables as needed. Can we detect 0.15 vs 1? Otherwise, I feel that this would constitute dropping 0.15 support, which would be a breaking change for Documenter.

**Comment by uncomfyhalomacro** [comment]
> Ah, right-right. But this would fail for anyone using Woodpecker 0.15? And this is theoretically possible, since it can be self-hosted.. actually.. I am a little bit confused -- does Woodpecker even offer a central service? Or is it always self-hosted?
> 
> I feel that to do this properly, we would need to version guard things, if that's something that can be done. I.e. use different sets of environment variables as needed. Can we detect 0.15 vs 1? Otherwise, I feel that this would constitute dropping 0.15 support, which would be a breaking change for Documenter.

Sure. I can help on that. I will check out the docs later. :D

**Comment by uncomfyhalomacro** [comment]
> Ah, right-right. But this would fail for anyone using Woodpecker 0.15? And this is theoretically possible, since it can be self-hosted.. actually.. I am a little bit confused -- does Woodpecker even offer a central service? Or is it always self-hosted?
> 
> I feel that to do this properly, we would need to version guard things, if that's something that can be done. I.e. use different sets of environment variables as needed. Can we detect 0.15 vs 1? Otherwise, I feel that this would constitute dropping 0.15 support, which would be a breaking change for Documenter.

Seems we can detect the version with `CI_SYSTEM_VERSION` I will see how to work with it once I am done with things. Possibly I will ping again for a code review next week

**Comment by mortenpi** [comment]
Re #2339, this one we can close, right?

**Comment by uncomfyhalomacro** [comment]
Yes. Closed now. As for the superseding PR, 1.0.x and 2.0.x are compatible except some removed support for other environmental variables pre-1.0.x

**Pull request closed without merging**
