### PR TITLE
prepare for macrocall having a source location argument

### PR DESCRIPTION
**Pull request by vtjnash**
JuliaLang/julia#21746

(will need https://github.com/JuliaLang/Compat.jl/pull/355 to be merged and tagged first, then restart CI here)

### CODE REVIEW

**Comment by mortenpi** [comment]
Since I'm not really familiar with the docsystem code -- this is an enhancement that will be available with 0.7 / master, right?

**Comment by vtjnash** [comment]
Yes, this is for a PR against Julia master

**Comment by mortenpi** [comment]
But 0.7 builds won't fail without this, right? I am wondering whether I should worry about backporting.

**Comment by vtjnash** [comment]
They'll start to fail once https://github.com/JuliaLang/julia/pull/21746 is merged, which is why this needed to be done first

**Comment by mortenpi** [comment]
Ah, I'll tag a patch release for Documenter asap then.

**Comment by vtjnash** [comment]
Thanks :)

**Pull request merged**
