### PR TITLE
add trailing slash to version selector URL

### LINKED ISSUE #2022: Trailing slashes for the target URL of the version selector
What would I need to change to get that?

It's causing me some problems deploying with netlify without ( see: https://github.com/JuliaPlots/PlotDocs.jl/pull/337 )

### PR DESCRIPTION
**Pull request by BeastyBlacksmith**
Fix #2022 .

I haven't tested that yet.

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by mortenpi** [comment]
Thanks!

**Comment by BeastyBlacksmith** [comment]
Seems there is something happening that undos this:

Bildschirmfoto vom 2023-01-23 13-33-53

**Comment by mortenpi** [comment]
It looks correct to me in [Documenter dev docs](https://documenter.juliadocs.org/dev/):

image

Note: this is only available on Documenter `master`. It wasn't in the release I tagged yesterday.

**Comment by BeastyBlacksmith** [comment]
> Note: this is only available on Documenter `master`. It wasn't in the release I tagged yesterday.

I see, the release notes made me think that.

**Comment by mortenpi** [comment]
Yeah, we should actually disable the automatic generation of the changelog, since it doesn't play well with backports.

**Comment by toollu** [comment]
> Note: this is only available on Documenter `master`. It wasn't in the release I tagged yesterday.

Any plans to release this soon? We just hit this.

**Comment by mortenpi** [comment]
There are a few [unresolved issues](https://github.com/JuliaDocs/Documenter.jl/milestone/107), in particular #2081. So the exact ETA is unclear. However, you can always use the latest master for your own docs.

**Pull request merged**
