### PR TITLE
Set version to 0.25.0

### PR DESCRIPTION
**Pull request by mortenpi**
Time to get the enhancements and bugfixes that have accumulated on master out, open PRs can be postponed to 0.26.

### CODE REVIEW

**Comment by mortenpi** [comment]
@fredrikekre We have test failures because we need to install DocumenterTools when testing. But it is not compatible (in the `[compat]` sense) with Documenter 0.25. Any way we could make it work?

One way is to push to DocumenterTools master and add Manifests here, but that's a bit ugly. Another way would be to tag a version of DocumenterTools that already is declared to be compatible with 0.25.. but I don't know if that is allowed in General?

**Comment by fredrikekre** [comment]
> Another way would be to tag a version of DocumenterTools that already is declared to be compatible with 0.25.. but I don't know if that is allowed in General?

Yea you can do that.

**Comment by fredrikekre** [comment]
If there are no changes needed in DocumenterTools for Documenter 0.25 we could also update the compat bounds in the registry.

**Comment by mortenpi** [comment]
> If there are no changes needed in DocumenterTools for Documenter 0.25 we could also update the compat bounds in the registry.

We'd need to update the `Project.toml` there sooner or later though, so I feel that tagging a new release is actually the cleaner solution here.

**Comment by mortenpi** [comment]
I'll go ahead and merge and tag this (finally) as soon as the tests pass. We can have the 0.25 release be a bit less conservative than usual about new features/enhancements, and rapidly tag 0.25.x releases as the open PRs get merged.

**Pull request merged**
