### PR TITLE
add OhMyREPL.jl to examples

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Thanks, #258 caused a conflict here. Could you do a quick rebase?

**Comment by MichaelHatherly** [comment]
btw, OhMyREPL is brilliant!

**Comment by KristofferC** [comment]
Thanks a lot. Comments like that gives me inspiration to work more on it :). Documenter is also really awesome and getting better and better all the time.

**Comment by KristofferC** [comment]
I just made a new one, it was faster than having to fix my remote and rebase etc.

**Pull request closed without merging**
