### PR TITLE
Current package as a dep in docs/Project.toml

### PR DESCRIPTION
**Pull request by AsafManela**
The failure in the script is highly uninformative. Such a note would have saved me some time.

### CODE REVIEW

**Comment by fredrikekre** [comment]
I am not sure what you mean, can you clarify what you did and what failed?

**Comment by fredrikekre** [comment]
Ah, thanks for the clarification! Turns out we can "fix" this by switching the order of the `instantiate` and the `develop`, so maybe we should apply
````diff
diff --git a/docs/src/man/hosting.md b/docs/src/man/hosting.md
index 1787afc..82fb811 100644
--- a/docs/src/man/hosting.md
+++ b/docs/src/man/hosting.md
@@ -120,8 +120,8 @@ jobs:
       julia: 1.0
       os: linux
       script:
-        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
-                                    Pkg.develop(PackageSpec(path=pwd()))'
+        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
+                                               Pkg.instantiate()'
         - julia --project=docs/ docs/make.jl
       after_success: skip
 ```
````

and maybe we don't need this extra note added in this PR. Thoughts?

**Comment by AsafManela** [comment]
Yes! That sounds more robust than the note.

**Comment by fredrikekre** [comment]
Do you wanna update the PR?

**Comment by fredrikekre** [comment]
Did you forget to `git add` the other change?

**Comment by AsafManela** [comment]
Not a pro gitter yet... What exactly did you want me to do? I don't know how to merge just your last commit from an upstream branch that has other changes as well.

**Comment by fredrikekre** [comment]
I was mostly wondering if you wanted to update this PR to include the change I suggested in the comment.

**Comment by AsafManela** [comment]
OK, this should do the trick. Thanks!

**Pull request merged**
