### PR TITLE
Docs - whitespace ssh public key generation correction

### LINKED ISSUE #778: Mistake in Documentation - SSH Deploy Keys
This is in the stable documentation as of today, in the section 'SSH Deploy Keys':

> Add the public ssh key to your settings page for the GitHub repository that you are setting up by following the .../settings/key link provided. Click on Add deploy key, enter the name documenter as the title, and copy the public key into the Key field. Note that you should include no whitespace when copying the key. Check Allow write access to allow Documenter to commit the generated documentation to the repo.
> 
> Next add the long private key to the Travis settings page using the provided link. Again note that you should include no whitespace when copying the key. In the Environment Variables section add a key with the name DOCUMENTER_KEY and the value that was printed out. Do not set the variable to be displayed in the build log. Then click Add.

There seems to be two issues here:

For Github to accept the public key there must be a **single space** after "ssh-rsa".

The public key was followed by a space and the name of the computer it was generated on. Both the space and the computer name had to be removed for Github to accept the key.

### PR DESCRIPTION
**Pull request by moustachio-belvedere**
(hopefully) fixes #778

### CODE REVIEW

**Comment by mortenpi** [comment]
Thanks! It is probably good to clarify what whitespace we're referring to here. Although, it seems that GitHub is not picky (any longer?) about the amount of whitespace before and after the key as far as I can tell. But you do need to get the spaces right I think.

However, I am not sure what you mean w.r.t the `user@hostname` -- you don't have to remove it. E.g. the following key can be added without problems as far as I can tell:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNTxbtmG1IPxzeKsTVfdgFP0XOgmYdPhWKABzyCj2NyLgcVM+5e9+iVm9uQx1XRJ2ZUZBMCl4T7nkL6MzNusaH2OodNK7xQJggu5x75qRn2pI30qQAgxFVmtTbsPYtjgLVWfWLriYhk45iGJbqGKZGlivPgOvEXlO56ifUYwW0SV+qcjjDE873Suw/rJ8RlnHzEsgsLiI5BUBRT6rNOsswqqOR3/KtoynXycWUOD2AdF0IAO5GGW7h8exRanTUwJW4AS/HtSpw++X1dCxXf/HkdUqKNj3W0CNPA7GqDem9sW0pJx1zH1B44s5t3zS9nUjzQlgbG2QUSWbi6REJgPkF mortenpi@sandfly
```

**Comment by moustachio-belvedere** [comment]
No problem. Thanks for your work on such a great package!

I must admit now I don't remember all the exact permutations I tried (this was a few days ago, the day I posted this PR) before I got it working but it was definitely around 5 or 6 different ways and in the end it only worked when I deleted `user@hostname` and had one space after `ssh-rsa`. So this was as of a few days ago. I'm at JuliaCon at the moment (maybe you are too!) but when I'm back home I will test a few variations on Github to see what works!

**Comment by bramtayl** [comment]
I've been having problems with this too...

```julia
make_keys(ssh_keygen_file = settings("ssh_keygen_file")) = mktempdir() do temp
    cd(temp) do
        @info "Generating ssh key"
        filename = ".documenter"
        try
            run(`$ssh_keygen_file -f $filename -N ""`)
        catch x
            if isa(x, Base.UVError)
                error("Cannot find $ssh_keygen_file")
            else
                rethrow()
            end
        end
        read(string(filename, ".pub"), String),
            read(filename, String) |> base64encode
    end
end
```

This is my code for generating SSH keys, but I'm consistently gettting the `malformed base64 sequence` error

**Comment by mortenpi** [comment]
@bramtayl: Do you mean when adding the SSH key generated this way to Travis and running Documenter? Documenter basically just `base64decode`s the key, so it looks like something is going from when copying?

**Comment by bramtayl** [comment]
I hope the following info isn't private: here's the output I get:
```julia
[ Info: Generating ssh key
Generating public/private rsa key pair.
Your identification has been saved in .documenter.
Your public key has been saved in .documenter.pub.
The key fingerprint is:
SHA256:0tfqUAeY4YHUjbkz3jdI0lGcNIEaDfhl8VkLNFt9VGE hp@LAPTOP-OMA551S0
The key's randomart image is:
+---[RSA 2048]----+
|     ..++*.BOooE=|
|      o.==B.oO..o|
|       .+B..+ . .|
|       .B oo     |
|      ..S*o.o    |
|       ..oooo    |
|        . .. .   |
|         o       |
|          .      |
+----[SHA256]-----+
[ Info: getting github keys
[ Info: creating github key
.documenter
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1i2MNCLDU/CyBeSazkVtKCuDoehCsVE277mVce1Ce4gEnMKme08fU59NHo1tH+m3h2V0A7A0QJzf8qaYnQ2GMCom36rrhbI0/bfcM09+AzuvcmpLnXJ1PI2rIuAMQFo9hi0cxXoWYWwUn0LiBMVg8DQodlrR0zyuAP89zRkdhH7eQYz6LPp0KsuojumGFqBRhdeJ9nL72Uio24LaEa6atHjyqfhY0Wit6L8N117bsgN7IiTO6j7uLPr4ZPFOJHhCCb2j5/2gvhWtr8yB2kzKOqXCiNcOE9dzKne5MFHswDxlB0+bTTyNyrqt0rZnizfdNl5gjeI4ELcY1dMhHnEWZ hp@LAPTOP-OMA551S0

[ Info: getting travis keys
[ Info: deleting travis key
[ Info: creating travis key
DOCUMENTER_KEY
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdFl0akRRaXcxUHdzZ1hrbXM1RmJTZ3JnNkhvUXJGUk51KzVsWEh0UW51SUJKekNwCm50UEgxT2ZUUjZOYlIvcHQ0ZGxkQU93TkVDYzMvS21tSjBOaGpBcUp0K3E2NFd5TlAyMzNETlBmZ003cjNKcVMKNTF5ZFR5TnF5TGdERUJhUFlZdEhNVjZGbUZzRko5QzRnVEZZUEEwS0haYTBkTThyZ0QvUGMwWkhZUisza0dNKwppejZkQ3JMcUk3cGhoYWdVWVhYaWZaeSs5bElxTnVDMmhHdW1yUjQ4cW40V05Gb3JlaS9EZGRlMjdJRGV5SWt6CnVvKzdpejYrR1R4VGlSNFFnbTlvK2Y5b0w0VnJhL01nZHBNeWpxbHdvalhEaFBYY3lwM3VUQlI3TUE4WlFkUG0KMDA4amNxNnJkSzJaNHMzM1RaZVlJM2lPQkMzR05YVElSNXhGbVFJREFRQUJBb0lCQUV2MlBNWFJZeHhiUDh3VgpBMHFUZ1owam5DUHFIMXZjRW9LV0o3ZGdxY1V4VDhZMEtHVWF2RHlybTg0WDNqUHA1MXhlOVBsVHk4dDhmWUt0CkFhYmdITXJhQmZIOHQ2Rm5LRnJvQ2oxRjBmazFtNTg4MWtjVWk0WDNqZERhbmYxM1V4cy9pZFJ3ZG5uZmEvTFMKOU1DcUF2OXRmVlFRSVFYWFFaNXlGTDFwSktqUVJkdTNrMDR2eFdWUkpId2tHZWJRTmxYcU1WVHQ2ZERxNi9VOQpDT3o4M2hlNGxwZEJkMmhuUXdBTWIyTklyakRpV2NxS0hOQWlvcnhOWXdtZHNBZ01VcHJlc1J4UmFIOVFXOVF5CnA5TmdDYUtaS0huUkNJekozbXdKOXVEZXhlbmNkNk0rYy9HZ2dmQUZFa2NTOENDTTJmK3dtMVFRdzAva2hhWlcKTVFTcWorRUNnWUVBNVozL2JCZ0VvNjFuMTJDd0JhbDBOa2g3ZXQvZFdXdVlhNDZsai9FckxVWXZUWnBkdlBLbgpIeVBFLzhueERTNXFLQUlXQ3BlVHJpdzMzc0FIMmdUT2g1Qm1NUUFhMmJjSTdFNGVYMWM3SEZ2NTBXRUpncE5FCmdXQlcwckZNcEZzSUI2THo5WGowTjBwWnRtN1pNSnJBcVZJZ2JQUE1GZ2pzc1RYSytqcTh0bFVDZ1lFQXltZGUKc2xhRTFLRE5saDY2blM2VUlBKy82a1F3Y1lWZzlJOHFSVHVtRjFYMGRTUlQ5OW03ZEsyblpSRkVHUzBMMTArSQp4TzBrWkhhYmUzTFFwTFNsbnhqU2tZTjArRjNhY0dZQ1dWM2JPUzZJbTZrZW81WGRQZHdPVzVCcjRHTEdmWEw2Clk0SHZDM0lKUGl6SStTcUJUYVFpaXFVK3Vid3ZSaWJiQW1WcWJqVUNnWUVBcGtvRVB0NHVEZk41TG91QkxyaUgKeHdBN0hNT2ZaREQ5MDNjZEE5K2VhMDFXMkphZ3FFUDdNQndSZ1VWWVl6bG4rODEyOVBqTkpPZzFGZ1p3S1Q0dAo3Qk54VHE5S3dyMUJveEQ0QWdnRWNRZFRKb1ZtQThCdmJscTh4aDFNNmdKYkVGeTgzTnRaMGVqd2k2US9lbW00CmVXZFd3RkRYVG1Yc05ISkdxMjE2V1hrQ2dZQWNObUpsdTFlU2g4T0FURkk0dkpoYkM3YjFnWUc3SVJ0Tm0zTUoKNlhHU1NTSGsvaVpTSXVCVk9DdGdGQk1JNjFWK01wRGUyaXM3Y2Fqa2dUR0I4OGd1TC9pUjNkLzlDcC83RU16OQpCZThidmxlK1VzbDVoZGNyMnpPSkljMVhubzBLU1crTFZUNHJ1ejU4a3lPRVQ1OXNZaGVLZWRRUGNhS3BSWnM3CmIwVnhqUUtCZ0NyUnZKNUJ2Rkw1aXBTWlY3UW14UG53TGEzWVowd0JqcVpiVmFuMDBQRWs4Z3pkaVdhQVFvNkoKMVpOc3NYemJOOTJCNmptWjEyNW1ENElTSXJEanRDa0duc1pGV2JYLzVIRS9Gd3pYL2MyS1NYcTBxdWNvRVU0YgprRkhWdld5ZVBqR1B6aFhTbXdRYm5Yck15aEcvelF1eFZzdXZFd2hxK29jTWFjRTRiU3NTCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```
My program is supposed to use the REST API to add the keys to GitHub and Travis, but I tried copying and pasting manually and it still didn't work.

**Comment by mortenpi** [comment]
> I hope the following info isn't private.

It is if you are actually using these keys. If you do, please remove them from GitHub etc. right away as they have been exposed now.

If these were freshly generated keys and you are not using them, then there is not need to worry.

**Comment by bramtayl** [comment]
Yeah I'm not using these keys

**Comment by mortenpi** [comment]
As for the issue: if you add the complete encoded private key as `DOCUMENTER_KEY`, it _should_ work. I.e., from the example you posted, this full string without any newlines at the beginning or the end.

```
LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdFl0akRRaXcxUHdzZ1hrbXM1RmJTZ3JnNkhv ... 5ZVBqR1B6aFhTbXdRYa5Yck15aEcvelF1eFZzdXZFd2hxK29jTWFjRTRiU3NTCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

Note that I have removed a part of the key in the middle and replaced it with an ellipsis. Of course, one should copy the full key.

The GitHub key (the one starting with `ssh-rsa`) is easier -- if GitHub accepts it, it should be all good.

**Comment by bramtayl** [comment]
AHHH GOT IT I just needed to sneak a chomp before the base64encode

**Comment by mortenpi** [comment]
I was wondering about something like that. We don't do it in `Travis.genkeys` though, but maybe we should. Are you on Windows? I guess there could be a platform-specific difference in what `ssh-keygen` outputs.

**Comment by bramtayl** [comment]
Might just be worth pointing people over to OnlinePackage? I'm hoping to keep it relatively stable now that 1.0 comes out, and it will submit keys to github and travis as well.

**Comment by mortenpi** [comment]
@bramtayl You wouldn't be willing to incorporate some of the Documenter-related backend stuff into [DocumenterTools](https://github.com/JuliaDocs/DocumenterTools.jl) by any chance?

**Comment by bramtayl** [comment]
I mean, you can take code you want. I don't see any clear way of transferring just a subset of the API code, though, because you need to have settings for the log in info and the package codes etc.

**Comment by mortenpi** [comment]
GitHub is no longer as picky about whitespace and the reference to whitespace in the text was altogether removed in #838, hence this is no longer relevant.

**Pull request closed without merging**
