### PR TITLE
Scale figures to textwidth in latex writer

### PR DESCRIPTION
**Pull request by pfitzseb**
This isn't an ideal solution since we're also going to *upscale* small images, but fixing that [is nontrivial](https://stackoverflow.com/questions/122348/scale-image-down-but-not-up-in-latex).

### CODE REVIEW

**Comment by mortenpi** [comment]
What about [`adjustbox`](https://tex.stackexchange.com/a/96468/127437)?

**Comment by pfitzseb** [comment]
Yeah, that's also one of the solutions mentioned in the stackoverflow post I linked. Is just adding packages [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/latex/documenter.sty) ok?

**Comment by mortenpi** [comment]
Yep, I'd put them in the `.sty`. The only thing that would be good to check is to make sure that it still builds fine with the Docker image, i.e. that we have `adjustbox` available in the image.

**Comment by pfitzseb** [comment]
Alright, changed to the `adjustbox` setup and can confirm the docker build still works fine.

**Comment by mortenpi** [comment]
LGTM, will merge shortly. Thanks @pfitzseb!

**Pull request merged**
