### PR TITLE
Issue #1575 added overflow-y hidden

### PR DESCRIPTION
**Pull request by LazyScholar**

### CODE REVIEW

**Comment by fredrikekre** [comment]
What happened here?

**Comment by LazyScholar** [comment]
I deleted my branch? Nothing more or did i do something else wrong?

**Comment by fredrikekre** [comment]
It closed the PR, but I remade the changes in https://github.com/JuliaDocs/Documenter.jl/pull/1651.

**Comment by LazyScholar** [comment]
Oh is think i understand... i did something wrong i mistook the merge message af2f513 as merged to the repo and deleted my branch. I should have looked closer sorry.

**Comment by fredrikekre** [comment]
No worries, I just synced your branch with master

**Pull request closed without merging**
