### PR TITLE
WIP remove stable

### PR DESCRIPTION
**Pull request by fredrikekre**
Trying to do this in small steps. This PR removes `stable`.

### CODE REVIEW

**Comment by fredrikekre** [comment]
What should we recommend that people set as their `html_canonical`? The docs to the latest major release? In case of Documenter that would be `https://juliadocs.github.io/Documenter.jl/v0` then? Which symlinks to the latest `v0.X`?

**Comment by mortenpi** [comment]
Actually.. maybe for packages it makes sense to have `stable/` just for this reason, always pointing to the latest released version?

**Comment by fredrikekre** [comment]
So maybe keep deploying to `stable` as an alias for latest release then maybe? We can let people use a configurable version selector to exclude `stable` from that instead.

**Comment by fredrikekre** [comment]
But it could be a symlink instead of an exact copy.

**Comment by mortenpi** [comment]
We should definitely make it a symlink. Let's keep it as a default for packages then, but we need an option to disable it (e.g. for base).

**Comment by fredrikekre** [comment]
(I am reworking this for another PR instead).

**Pull request closed without merging**
