### PR TITLE
Remove the link when we are symlinking

### PR DESCRIPTION
**Pull request by fredrikekre**
Something else is wrong, I wonder if `islink` does not work on the cloned repo or something...
Trying to debug here.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Ok, the problem is that `stable` is a directory that exists... We can remove that, from Documenter of course, since Documenter will symlink it, but this could be bad if a user have set `devurl = "stable"` for some weird reason. I guess we can special case for now the Pair `"stable" => "v^"` and remove in only that case. I suspect that, at least to start with, most people will just use the defaults for `versions = ...` anyway...

**Comment by mortenpi** [comment]
We could add a check though, to make sure that the version selector does not try to create `devurl`, and warn/fail the build if it does.

**Comment by fredrikekre** [comment]
Not sure I understand what you mean; I removed the special casing of  `"stable"` and we now always remove the link. It should be fine to trust the user input here. We also filter out things like `"dev" => "dev"` https://github.com/JuliaDocs/Documenter.jl/blob/58e1883e183dacf7ecda39c24e76df765aa085db/src/Writers/HTMLWriter.jl#L551 so we never accidentally remove what we are trying to link to.

**Comment by mortenpi** [comment]
What will happen if `devurl = "stable"` and you also have `"stable" => "v^"`? Won't it delete the `master` docs you just deployed?

**Comment by fredrikekre** [comment]
Ah good catch. We should assert that a link does not point to another link.

**Comment by mortenpi** [comment]
> Or should we check explicitly that we never remove the `devurl` folder?

I don't think it would hurt to have that check, just in case. It's a contradiction in `deploydocs`' arguments. Just a small loop in `git_push!` that checks that none of the `symlinks` firsts are equal to `devurl`?

**Comment by fredrikekre** [comment]
Yea, might as well catch that corner case.

**Comment by fredrikekre** [comment]
This could be annoying if anyone wants to keep `latest` in the selector(`versions = ["latest" => "dev"]`), but use `devurl = "dev"`. But I guess one has to manually remove stuff from `gh-pages` then.

**Comment by mortenpi** [comment]
LGTM! I'll merge this to get the master doc builds passing again.

**Pull request merged**
