### PR TITLE
Remove references to 0.5

### PR DESCRIPTION
**Pull request by PallHaraldsson**

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
Seems STABLE doc also outdated, say older versions/0.4 was supported/is in old code.

**Comment by mortenpi** [comment]
For a package dealing with documentation, I should really take better care of its documentation. There's also a reference to 0.5 in the README -- could you also remove that? Docs for stable will update once 0.12 gets tagged.

**Comment by fredrikekre** [comment]
Is this actually needed? Documenter still works on 0.5.

**Comment by mortenpi** [comment]
`master` does not anymore. The current 0.11 branch is the last one that will support 0.5.

**Comment by fredrikekre** [comment]
Well, yea, but there are still releases that work on 0.5. From the README the impression now is that it only works on 0.6 and above. Does not really matter though.

**Pull request merged**
