### PR TITLE
Tone down admonition coloring

### PR DESCRIPTION
**Pull request by fredrikekre**
This patch tones down the admonitions by removing the background color in the admonition header and the lighter color in the body. Instead the admonition header text is colored.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Increased the border thickness a bit too since otherwise it was a bit difficult to see the color of the borders. I am happy with this now.

**Comment by mortenpi** [comment]
For consistency, should we increase the thickness of the docstrings blocks and pre blocks maybe?

image

**Comment by fredrikekre** [comment]
Maybe? And also round the corners like admonitions then?

**Comment by mortenpi** [comment]
> And also round the corners like admonitions then?

Or make admonitions rectangles? :sweat_smile:

**Comment by fredrikekre** [comment]
Updated, and also the `border-bottom` of docstring headers.

**Comment by fredrikekre** [comment]
> and also the border-bottom of docstring headers.

Maybe this isn't needed actually?

**Comment by mortenpi** [comment]
> > and also the border-bottom of docstring headers.
> 
> Maybe this isn't needed actually?

Do you mean getting rid of the border altogether or keeping it `1px`? I think my mild preference is to just keep that `1px`.

image

image

image

**Comment by fredrikekre** [comment]
> Do you mean getting rid of the border altogether or keeping it 1px?

I mean that increasing it isn't needed and agree that 1px looks nicer.

**Review by mortenpi — APPROVED** [review]
LGTM! I don't think we have anything else coming, so shall we tag 1.5.0 right away?

**Comment by fredrikekre** [comment]
I could finish up #2496 before, but doesn't really matter.

**Comment by mortenpi** [comment]
Happy to hold off until then. The two changes go together nicely.

**Pull request merged**
