### PR TITLE
Compat for base64encode, base64decode

### PR DESCRIPTION
**Pull request by fredrikekre**
Should fix https://github.com/JuliaLang/julia/issues/24857

### CODE REVIEW

**Comment by henrykironde** [comment]
@fredrikekre, Could be nice if you added some test for base64encode base64dencode

**Comment by fredrikekre** [comment]
What do you mean? https://github.com/JuliaLang/julia/blob/master/stdlib/Base64/test/runtests.jl

**Comment by henrykironde** [comment]
@fredrikekre, sorry I didn't see that part

**Comment by mortenpi** [comment]
Thanks! Will merge and tag once Julialang/METADATA.jl#12295 is merged.

**Pull request merged**
