### PR TITLE
Fix `submodules` to avoid stackoverflow

### LINKED ISSUE #392: Error using Documenter for Gtk.jl
Hi, I tried to use Documenter for the package Gtk.jl and get either an error when invoking `make.jl` form the REPL or a segmentation fault when invoking `make.jl` from the command line.

Here is my make.jl

```
using Documenter, Gtk

makedocs(
    format = :html,
    modules = [Gtk],
    sitename = "Gtk.jl",
    authors = "...",
    pages = [
        "Home" => "index.md",
        "Manual" => ["manual/gettingStarted.md",
                    ],
    ],
)
```

and here is the error

```
ERROR: LoadError: StackOverflowError:
 in sort!(::Array{Symbol,1}, ::Int64, ::Int64, ::Base.Sort.InsertionSortAlg, ::Base.Order.ForwardOrdering) at ./sort.jl:0
 in sort!(::Array{Symbol,1}, ::Int64, ::Int64, ::Base.Sort.MergeSortAlg, ::Base.Order.ForwardOrdering, ::Array{Symbol,1}) at ./sort.jl:311
 in sort!(::Array{Symbol,1}, ::Int64, ::Int64, ::Base.Sort.MergeSortAlg, ::Base.Order.ForwardOrdering, ::Array{Symbol,1}) at ./sort.jl:316 (repeats 7 times)
 in sort!(::Array{Symbol,1}, ::Base.Sort.MergeSortAlg, ::Base.Order.ForwardOrdering) at ./sort.jl:405
 in sort!(::Array{Symbol,1}, ::Base.Sort.MergeSortAlg, ::Base.Order.ForwardOrdering) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in submodules(::Module, ::Set{Module}) at /Users/knopp/.julia/v0.5/Documenter/src/Utilities/Utilities.jl:179
 in submodules(::Module, ::Set{Module}) at /Users/knopp/.julia/v0.5/Documenter/src/Utilities/Utilities.jl:184 (repeats 20941 times)
 in submodules(::Module) at /Users/knopp/.julia/v0.5/Documenter/src/Utilities/Utilities.jl:179
 in submodules(::Array{Module,1}) at /Users/knopp/.julia/v0.5/Documenter/src/Utilities/Utilities.jl:174
 in #Document#5(::String, ::String, ::String, ::Symbol, ::Bool, ::Bool, ::Bool, ::Symbol, ::Bool, ::Array{Module,1}, ::Array{Pair{String,B},1}, ::Array{String,1}, ::String, ::String, ::String, ::Array{Any,1}, ::Type{T}) at /Users/knopp/.julia/v0.5/Documenter/src/Documents.jl:252
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{Documenter.Documents.Document}) at ./<missing>:0
 in #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at /Users/knopp/.julia/v0.5/Documenter/src/Documenter.jl:158
 in (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/knopp/.julia/v0.5/Gtk/docs/make.jl, in expression starting on line 3
```

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Fixes #392. @tknopp, could you confirm whether this fixes the Gtk problem for you, thanks.

### CODE REVIEW

**Comment by tknopp** [comment]
yep, thanks!

**Comment by MichaelHatherly** [comment]
Great, thanks. Now just need to duplicate that error without installing Gtk.

**Comment by tknopp** [comment]
why? for unit test?

**Comment by MichaelHatherly** [comment]
Yes, needs a test, I'll take a look at what exactly is happening later this afternoon.

**Comment by MichaelHatherly** [comment]
Seems like it was being caused by a cycle in the exported modules of Gtk, namely `GtkShortNames` was exporting it's parent `Gtk`:

```
julia> :Gtk in names(Gtk.ShortNames)
true
```

New code for `submodules` should handle those kind of things fine though.

**Comment by tknopp** [comment]
I have prepared Gtk.jl to make use of Documenter.jl. Travis is obviously failing but this will hopefully change once this PR is merged. Thanks for the quick fix!

**Comment by MichaelHatherly** [comment]
I'll tag `0.8.8`, which will have this fix, once AppVeyor has caught up.

**Pull request merged**
