### PR TITLE
Improve the warning for an unexpected dollar sign in a Markdown file

### PR DESCRIPTION
**Pull request by odow**
I was looking into https://github.com/JuliaDocs/Documenter.jl/issues/2288

The issue is that by the time we notice the value, we've lost the original source file and line information.

@mortenpi might have some ideas for how to get it back?

cc @kellertuer

### CODE REVIEW

**Review by fredrikekre — APPROVED** [review]

**Comment by mortenpi** [comment]
Another way would be to do the check somewhere earlier in the pipeline though. Would also avoid code duplication.

**Comment by odow** [comment]
Good by me. (Except for the status failures?)

**Comment by mortenpi** [comment]
> Except for the status failures?

I think they're unrelated..

**Comment by mortenpi** [comment]
It looks like the Coveralls failures resolved themselves.

**Pull request merged**
