### PR TITLE
Adding padding to menu's element on-hover

### PR DESCRIPTION
**Pull request by Hetarth02**
This PR aims to close Issue #1899.

### CODE REVIEW

**Comment by Hetarth02** [comment]
@mortenpi I don't know why it is showing 17 commits?

I have my forked synced with the `master` branch. So, to make things clear I have only made changes to one `scss` file which could been seen in the `Files changed` menu.

**Comment by mortenpi** [comment]
Let's discuss how we want to change this in #1899.

---

You also need to update the CSS files. I don't think we have the process documented anywhere, but you can [use DocumenterTools](https://github.com/JuliaDocs/DocumenterTools.jl/blob/c1af03618b9d1e9b50e9b6a472d2c4115dab6be5/src/Themes.jl#L68-L72) for that. I usually would do something like:

```
pkg> activate --temp
# Assuming you're in Documenter/, this will add your Documenter dev checkout as a dev. dependency:
pkg> dev .
# You need a special DocumenterTools tag (because the standard versions are not compatible with 0.28):
pkg> add DocumenterTools#documenter-v0.1.14+0.28.0-DEV
julia> using DocumenterTools
julia> DocumenterTools.Themes.compile_native_themes()
```

> I have my fork synced with the master branch.

You have extra commits on your master branch though, which is why they show here. The general practice is to create a new branch from the current master for each PR you want to open. That way you don't run into this. It's fine for this PR though -- we'll squash merge the PR anyway, so the intermediate commits won't affect anything.

**Comment by Hetarth02** [comment]
> You also need to update the CSS files. I don't think we have the process documented anywhere, but you can [use DocumenterTools](https://github.com/JuliaDocs/DocumenterTools.jl/blob/c1af03618b9d1e9b50e9b6a472d2c4115dab6be5/src/Themes.jl#L68-L72) for that. I usually would do something like:

It would also be helpful to add some documentation regarding this. Do we have something lilke a `CONTRIBUTING.md`?

**Comment by mortenpi** [comment]
> It would also be helpful to add some documentation regarding this. Do we have something lilke a `CONTRIBUTING.md`?

We have this: https://documenter.juliadocs.org/stable/contributing/

**Comment by Hetarth02** [comment]
I am closing this PR for the time being. I will make new PR/reopen this PR later.

**Pull request closed without merging**
