### PR TITLE
fix symbols on RHS of assignments in examples

### PR DESCRIPTION
**Pull request by KristofferC**
Possible fix to #612.

Would be nice if someone could try this on their docs, cc @Datseris

### CODE REVIEW

**Comment by Datseris** [comment]
Hi, to try this I first have to checkout `Pkg.checkout("Documenter", "kc/fix_symbol")`, correct?

**Comment by KristofferC** [comment]
Yeah, or you just use git from the command line like:

```
git fetch
git checkout kc/fix_symbol
```

**Comment by Datseris** [comment]
I am sorry, but it doesn't work.

It is stuck on 
```
Documenter: setting up build directory.
Documenter: expanding markdown templates.
```
for quite some time now, long enough to make me believe that there is something wrong.

**Comment by Datseris** [comment]
P.S.: I also had some issues while checking out (it was saying it cannot forward merge). I do not know how impactful this was.

**Comment by KristofferC** [comment]
That's interesting. Can I try it out myself. Do you use the master branch of some package?

**Comment by Datseris** [comment]
If you are talking about the packages I used when I encountered this, then no. The only thing you have to do is `Pkg.add("ChaosTools")` and then create a markdown file with:

```
using ChaosTools
using PyPlot

ds = Systems.logistic()
i = 1
pvalues = 2:0.001:4
ics = [rand() for m in 1:10]
n = 50
Ttr = 5000
output = orbitdiagram(ds, i, :r, pvalues; n = n, Ttr = Ttr)
```
and run it with `make.jl`. The problem arises when one replaces the last line with 
```
param = :r
output = orbitdiagram(ds, i, param, pvalues; n = n, Ttr = Ttr)
```

**Comment by mortenpi** [comment]
```julia
y = :x
@show y
```
is a simple MWE as far as I can tell.

**Comment by KristofferC** [comment]
Your MWE that shows this PR doesn't work? It seems to work ok locally:

screen shot 2017-12-26 at 21 12 39

**Comment by mortenpi** [comment]
No, it works fine. I just meant that it would be a simple test, but I missed that you already had it in the examples. I tested it with the `ChaosTools` example as too, it works fine. LGTM!

You're worried that it might break some existing `@example` blocks? It would be good to test with some package that has a lot of them, just in case.

**Comment by KristofferC** [comment]
I was thinking about the comment https://github.com/JuliaDocs/Documenter.jl/pull/614#issuecomment-353963447 explicitly saying that it doesn't work.

**Comment by Datseris** [comment]
Yeah I am rerunning it now, maybe it was some bad install or something

**Comment by Datseris** [comment]
```
Pkg.checkout("Documenter", "kc/fix_symbol")

INFO: Checking out Documenter kc/fix_symbol...
WARNING: Cannot perform fast-forward merge.
INFO: Pulling Documenter latest kc/fix_symbol...
WARNING: Cannot perform fast-forward merge.
INFO: No packages to install, update or remove
```

When I run `make.jl` it fails:
```
Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! failed to run code block.

UndefVarError(:r) [src\chaos\orbitdiagram.md]
```

Here is the code block with \`\`\`\@example header:
```
using DynamicalSystems
using PyPlot

ds = Systems.logistic()
i = 1
pvalues = 2:0.1:4
ics = [rand() for m in 1:10]
n = 50
Ttr = 5000
param = :r
output = orbitdiagram(ds, i, param, pvalues; n = n, Ttr = Ttr)
```

**Comment by Datseris** [comment]
I am guessing it's just coz of that "fast-forward merge" thing? I am not really experienced with git.

**Comment by mortenpi** [comment]
Yeah, I don't think it checked out the branch, which is why it is still failing. Could try Git directly to check out the branch? You should be able to do it within your Julia session:

```
julia> cd(Pkg.dir("Documenter"))
shell> git status
shell> git checkout kc/fix_symbol
```

**Comment by Datseris** [comment]
I am sorry, but I really couldn't make it work. I don't know what to do, git always shows me that I am on kc/fix_symbol but yet I can never properly checkout there. 

Anyway I think its clear that this is an issue from my end, and right now I don't want to spend more time on fixing git. Since you both confirmed that the PR works, I think you can go ahead and merge.

**Pull request merged**
