### PR TITLE
make Selectors.dispatch non-generated

### PR DESCRIPTION
**Pull request by shashi**
I really like organization of code that Selectors affords. But it's basically not extensible by other packages because `dispatch` is generated.

This patch is required for https://github.com/JuliaGizmos/DocServer.jl to work...

### CODE REVIEW

**Comment by mortenpi** [comment]
Theoretically the generated function should be a bit faster if `dispatch` would get called multiple time, but the difference should be negligible in practice -- `dispatch()` for a particular selector typically only gets called once. :+1: to making it extensible, LGTM!

Could you also update the related docstring?

**Comment by shashi** [comment]
Thanks. And yes I'll push the fixed docstrings soon.

**Comment by mortenpi** [comment]
Thanks!

**Comment by mortenpi** [comment]
By the way, DocServer looks interesting! If you don't mind me asking, where do you see DocServer mainly being used?

Is it OK for you to work with Documenter's `master` for a short while (a few weeks)?

**Comment by shashi** [comment]
DocServer will help me create examples which talk to Julia using web widgets... For example https://github.com/JuliaGizmos/InteractNext.jl could be used to plot a function where the visitor can vary some parameters. Something like @ChrisRackauckas's http://app.juliadiffeq.org/ode could then be done within Documenter docs. Another package that will soon be able to interact with Julia this way Makie.jl

Yes I'm fine using `master`.

**Comment by ChrisRackauckas** [comment]
Wooh, interesting. I'd like to migrate my app over to something less "low level" some time.

**Pull request merged**
