### PR TITLE
enable colored print for REPL output

### PR DESCRIPTION
**Pull request by aviatesk**
Won't be enabled for doctests (so I believe this should be safe).

### CODE REVIEW

**Comment by KristofferC** [comment]
Regarding doctests, how about producing colored output but stripping it before the comparison is made? I guess some people would not want that but it could be optional?

**Comment by aviatesk** [comment]
> it could be optional?

So that people can do something like ?
```julia
julia> printstyled("red"; color=:red)
\e[31mred\e[39m
```

Honestly, I'm not super willing to support it. Maybe we can delay the support to the future until when someone finds it useful ?

**Comment by KristofferC** [comment]
No, I meant so that people can still do:

````jl
```jldoctest
julia> @test 1==1
Test Passed
```
````

but have `Test Passed` written in green (like in the REPL).

**Comment by aviatesk** [comment]
Ah, I see. But it seems it requires much refactors in order to replace the contents of generated document with the actual outputs of doctests.

**Comment by KristofferC** [comment]
It was probably bad form of me to comment on this PR. It wasn't really meant as anything that should be done here, it was just a related thought I hade when I read the PR.

**Comment by fredrikekre** [comment]
Do you have an example of what this enables?

**Comment by aviatesk** [comment]
> It was probably bad form of me to comment on this PR. It wasn't really meant as anything that should be done here, it was just a related thought I hade when I read the PR description. I should just open a separate issue.

I see. Thanks for the clarification :)

> Do you have an example of what this enables?

An object may implement its own `show` method that may use color when enabled.
Probably the easiest repro would be something like:
```markdown
\`\`\`@example; ansicolor=true
struct Foo end
Base.show(io::IO, ::Foo) = printstyled(io, "Foo"; color = :blue)

Foo()
\`\`\`
```

**Comment by aviatesk** [comment]
@KristofferC so can this get merged (and maybe can we tag a patch release) ?

**Comment by fredrikekre** [comment]
Can you add a note in the changelog?

**Comment by aviatesk** [comment]
Sure. Added.

**Pull request merged**
