### PR TITLE
Move stream redirection later in pipeline

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Should help make output redirection less visible and easier to debug.

@mortenpi this *might* solve your `julia -i file.jl` troubles.

### CODE REVIEW

**Comment by mortenpi** [comment]
Yup, it fixes it. It now nicely goes to REPL after it's done with the file.

**Comment by MichaelHatherly** [comment]
Cheers, thanks for checking.

**Comment by mortenpi** [comment]
Just accidentally ran across this -- I guess [Expanders.jl#L31](https://github.com/JuliaDocs/Documenter.jl/blob/b77da2625f5b9cb17db563166f9a4c119df05e34/src/Expanders.jl#L31) should have been changed as well.

**Comment by MichaelHatherly** [comment]
Oops, thanks for catching that.

**Pull request merged**
