### PR TITLE
Force code padding

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by fredrikekre** [comment]
I suppose this makes it slightly more awkward to override these things yourself. Perhaps better to just modify my CSS file?

**Comment by pfitzseb** [comment]
Yea, I think that'd be better.

**Comment by pfitzseb** [comment]
Although maybe not? I've [removed the offending line in the original PR too](https://github.com/JuliaDocs/Documenter.jl/pull/1771/files#diff-c73999e36f0592994fec403b076e3f68418663eec065ebd604d2da123deed66e), so maybe it should be fixed in the Documenter CSS directly.

**Comment by fredrikekre** [comment]
What was your conclusion here? :slightly_smiling_face:

**Comment by pfitzseb** [comment]
I think this PR is fine -- you can still override the styling, but it'll just work with upstream themes.

**Pull request merged**
