### PR TITLE
Mh/fix path and list

### PR DESCRIPTION
**Pull request by MichaelHatherly**

### CODE REVIEW

**Comment by mortenpi** [comment]
Whoops :smile:.

The `fieldtype` case could perhaps be `<: Integer`? Although I'm not sure that we'd win much.. and lose performance?

LGTM by the way.

**Comment by MichaelHatherly** [comment]
Since it's toplevel code there shouldn't be any performance loss. `== Int` should be fine since the field itself is `Int`.

Thanks for reviewing, not sure what I was thinking with the original condition there.

**Comment by mortenpi** [comment]
> I was thinking

I actually thought it was my code (hence the whoops), but I now saw that this line was actually added later.

**Comment by MichaelHatherly** [comment]
Yeah, was my error, not yours :laughing:.

**Pull request merged**
