### PR TITLE
Backport #233, #234, #238, #239 to 0.3

### PR DESCRIPTION
**Pull request by MichaelHatherly**
Refs: #233, #234, #238, #239.

### CODE REVIEW

**Comment by mortenpi** [comment]
I'll take a look at #225. Shall we push that backport into here as well?

**Comment by MichaelHatherly** [comment]
> Shall we push that backport into here as well?

Yes, probably best to do that.

**Comment by mortenpi** [comment]
Just noticed that the branch is on your fork. Will you do the #239 backport?

**Comment by MichaelHatherly** [comment]
Yup, was just about to.

**Comment by MichaelHatherly** [comment]
Once this is merged would you like to tag `0.3.1`?

**Comment by MichaelHatherly** [comment]
(Looks like Travis is still having OSX build troubles, so merging/tagging can just wait 'til tomorrow I think.)

**Comment by mortenpi** [comment]
Yup, hopefully the OSX builds will complete overnight. I'll tag tomorrow.

**Comment by mortenpi** [comment]
I took the liberty of updating the PR title and adding refs to the OP.

**Pull request merged**
