### PR TITLE
docs: update remote links CHANGELOG entry

### PR DESCRIPTION
**Pull request by mortenpi**
@Datseris I slightly rephrased the "For upgrading" part of the repo link overhaul CHANGELOG entry. Do you think it improves it?

### CODE REVIEW

**Comment by mortenpi** [comment]
> This won't work anymore, right?

Well, the `modules` part is unchanged, but you do need to make sure that the packages are `Pkg.develop`ed, not `Pkg.add`ed (or you set `remotes` by hand). That said, there is #2232.. so maybe we'll get a better approach for this.

**Comment by Datseris** [comment]
I am confused. WHy do you need the remote for the packages? Is it so that one can access the source code? I thought this didn't work for "external" packages, clicking source. Does this mean that now clicking "source" button actually works on external packages as long as they are developed?

**Comment by Datseris** [comment]
In any case, `develop`ing all included modules is totally fine for me. I anyways build all documentations from a centralized repository which is cloned by all packages, so for me it is a simple change of altering the build function to first develop all given modules.

(https://github.com/JuliaDynamics/doctheme  and add a  simple `Pkg.dev` loop over `modules` in this line: https://github.com/JuliaDynamics/doctheme/blob/master/build_docs_with_style.jl#L42 )

**Comment by mortenpi** [comment]
> I thought this didn't work for "external" packages, clicking source. Does this mean that now clicking "source" button actually works on external packages as long as they are developed?

Yes!! E.g. you can look at the DocumenterTools docstrings here: https://documenter.juliadocs.org/dev/lib/public/#DocumenterTools

I'll just note here that the major motivator was actually the Julia standard libraries that are are hosted externally from the main Julia repo.

**Comment by Datseris** [comment]
Isn't there the (potential) downside that the links to the functiosn are resolved based on the _development_ version of a package, while in the majority of times you would want the source code of the _latest stable_ to be linked?

**Comment by Datseris** [comment]
Actually, this is an important point. Linking to stable versions is hugely important when building the documentation via a tagged release.

**Comment by mortenpi** [comment]
> Isn't there the (potential) downside that the links to the functiosn are resolved based on the development version of a package, while in the majority of times you would want the source code of the latest stable to be linked?

Sure. So you need to make sure you have the tag checked out, no main/master :slightly_smiling_face: It's true that this does require a bit more care when adding the packages though, and this should maybe be emphasized in the docs. But also https://github.com/JuliaDocs/Documenter.jl/pull/2232 would pretty much solve that.

That said, this question about what version of the other package to link to is exactly why I am actually not at all a fan of including these "external" docstrings like this.

**Pull request merged**
