### PR TITLE
Add purple coloring for todo-admonitions

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by mortenpi** [comment]
Where is this actually used in practice? This is not a standard admonition supported by the Markdown stdlib, right? My view generally has been that we only style admonitions that are also supported by the REPL etc., and custom stuff should be a plugin.

Could we add an example of it here? https://github.com/JuliaDocs/Documenter.jl/blob/5425664e91a1dedcf59bd32139d341f9271318e6/docs/src/showcase.md?plain=1#L101-L119

**Comment by fredrikekre** [comment]
> Where is this actually used

I just wanted nicely formatted todo-notes in the docs :) I can of course just add the necessary CSS locally.

**Comment by mortenpi** [comment]
I think my inclination here is not to deviate from the Markdown stdlib and the Julia REPL 🙁 I only wish it was easier to customize the themes and admonitions though. The ability to add custom ones would be useful though.

**Comment by fredrikekre** [comment]
I guess I just have to patch Markdown and REPL first then :)

**Comment by mortenpi** [comment]
> I guess I just have to patch Markdown and REPL first then :)

That's definitely one way to go about it :rofl:

**Comment by fredrikekre** [comment]
Just noticed that Github uses purple for the `Important` category; https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Review by mortenpi — APPROVED** [review]
LGTM. @fredrikekre, it's good to go, right? Sorry, this slipped through the cracks.

image

image

**Pull request merged**
