### PR TITLE
Fix PDF output format with `julia` code block.

### LINKED ISSUE #1118: The julia code block contains character `%` can not generate PDF format output.
Markdown code like this:
    
    ```julia
    1 % 2
    ```

will failed to generate PDF format output.

### PR DESCRIPTION
**Pull request by June-6th**
- Don't failed to generate PDF format with `julia` code block that
contain `%`.(Fixes #1118)
- Don't eat the last line of `julia` code block.

Before this PR:

Screenshot_20190829_190510

After this PR:

Screenshot_20190829_190630

### CODE REVIEW

**Comment by mortenpi** [comment]
Hmm, on my system at least this seems to break `⊻` rendering. This code block

````markdown
```julia
1 % 2
1 ⊻ 2
1 | 2
```
````

becomes

```tex
\begin{minted}[escapeinside=⊻⊻]{julia}
1 % 2
1 ⊻\unicodeveebar⊻ 2
1 | 2
\end{minted}
```

as it should. But that renders as

Screenshot from 2019-08-30 11-22-55

After having played around with this for a while, it seems that minted's escaping is pretty broken in general? Using `%` _should_ work in my opinion (like it does for `lstlisting`). `⊻` maybe does not work because it is non-ASCII?

This gist should reproduce it: https://gist.github.com/mortenpi/574735e33d0f2e9093681a45e37bfd80

---

As a general comment, I think, if we can, it would be better to have the same escaping logic for the `minted` and `lstlisting` blocks. I.e. if we change `escapeinside` for one, we should probably change it for the other. That should obviate the need for two `_print_code_escapes` functions.

**Comment by June-6th** [comment]
I can't reproduce your problem. My LuaTeX version is 1.07.0, what about you?

**Comment by mortenpi** [comment]
Right, I was wondering if it might be something like that. Mine is 1.0.4. But that's from the Ubuntu 18.04 repositories, so this will break things if we build with our current Docker image.

**Comment by mortenpi** [comment]
What seems to work is to add this to `documenter.sty`:

```tex
\newfontfamily\unicodevbarfont{DejaVu Sans}[Scale=MatchLowercase]
\newcommand\unicodevbar{{\unicodevbarfont ^^7c}}
```

and then do the code blocks as follows:

```tex
\begin{lstlisting}[escapeinside=||]
1 % 2
1 |\unicodeveebar| 2
1 |\unicodevbar| 2
\end{lstlisting}

\begin{minted}[escapeinside=||]{julia}
1 % 2
1 |\unicodeveebar| 2
1 |\unicodevbar| 2
\end{minted}
```

**Comment by June-6th** [comment]
It is perfect! It would be better  to let `⊻` and `|` use the same color as other operators.

**Comment by mortenpi** [comment]
> It would be better to let `⊻` and `|` use the same color as other operators.

Hmm. Do you mean that minted isn't highlighting them properly at the moment because we're doing the LaTeX magic?

**Comment by June-6th** [comment]
Yes, they are darker.

**Comment by mortenpi** [comment]
> Yes, they are darker.

I guess that would need getting the correct font color, thicknes etc. for the minted internals and applying it manually?

**Comment by June-6th** [comment]
This may be the easiest way to do it, because lstlisting do not have the problem.

**Comment by findmyway** [comment]
Hey @mortenpi ,

Is there any blocking issue or concern to merge this PR? 

The building pipeline for the pdf version of the Julia Documentation in Chinese has been broken for months due to the problem described above. It would be great to see this PR get merged.

Ref: https://github.com/JuliaCN/JuliaZH.jl/issues/85

**Comment by mortenpi** [comment]
I think it will still break the Docker image currently?

**Comment by mortenpi** [comment]
Ok, it doesn't actually break the Docker image, but PDFs built with it do not render correctly at the moment: https://github.com/JuliaDocs/Documenter.jl/pull/1119#issuecomment-526438867. Swapping the implementation to https://github.com/JuliaDocs/Documenter.jl/pull/1119#issuecomment-526453896 should work around that I think?

**Comment by findmyway** [comment]
> What seems to work is to add this to `documenter.sty`:
> 
> ```
> \newfontfamily\unicodevbarfont{DejaVu Sans Mono}[Scale=MatchLowercase]
> \newcommnd\unicodevbar{{\unicodevbarfont ^^7c}}
> ```
> 
> and then do the code blocks as follows:
> 
> ```
> \begin{lstlisting}[escapeinside=||]
> 1 % 2
> 1 |\unicodeveebar| 2
> 1 |\unicodevbar| 2
> \end{lstlisting}
> 
> \begin{minted}[escapeinside=||]{julia}
> 1 % 2
> 1 |\unicodeveebar| 2
> 1 |\unicodevbar| 2
> \end{minted}
> ```
> 
> Edit: should be DejaVu Sans Mono for this symbol.

Hi @June-6th , can you confirm this works and make the change correspondingly?

<hr>

> Right, I was wondering if it might be something like that. Mine is 1.0.4. But that's from the Ubuntu 18.04 repositories, so this will break things if we build with our current Docker image.

I think when https://github.com/JuliaDocs/Documenter.jl/issues/979 gets resolved, this will not be a big problem. (At least it's not a big problem for us right now. Because we are using a customized docker image [here](https://github.com/JuliaCN/JuliaZH.jl/blob/master/contrib/LaTeXWriter.jl#L6))

**Comment by June-6th** [comment]
@findmyway  Yes, it work well.

**Pull request closed without merging**
