### PR TITLE
Add support for deploying from Buildkite.

### PR DESCRIPTION
**Pull request by maleadt**
Modeled after GitLab, but I left out the slug and source since they seemed unused anyway.
Example of successful run: https://buildkite.com/julialang/cuda-dot-jl/builds/116

### CODE REVIEW

**Comment by maleadt** [comment]
Looks like this doesn't work on a non-PR:

```
[Info: [22m[39mDeploying to GitHub
┌Info: [22m[39m
│Buildkite config:
│  Commit branch: "master"
│  Pull request: "false"
│  Commit tag: ""
│Detected build type: preview
│- ✘ ENV["BUILDKITE_PULL_REQUEST"]="false" is a number
│- ✔ `push_preview` keyword argument to deploydocs is `true`
│- ✔ ENV["DOCUMENTER_KEY"] exists
└Deploying to folder "previews/PR0": ✘
[36m[1m[ [22m[39mInfo: [22m[39mDeploying to GitHub
┌Info: [22m[39m
│Buildkite config:
│  Commit branch: "master"
│  Pull request: "false"
│  Commit tag: ""
│Detected build type: preview
│- ✘ ENV["BUILDKITE_PULL_REQUEST"]="false" is a number
│- ✔ `push_preview` keyword argument to deploydocs is `true`
│- ✔ ENV["DOCUMENTER_KEY"] exists
└Deploying to folder "previews/PR0": ✘
```

I guess I need to filter out the PR if it's set to `false`.

**Comment by mortenpi** [comment]
Can't really test it myself, but LGTM. If it works and is good to go, them I'm happy to merge.

**Comment by jakebolewski** [comment]
LGTM, it would be great to tag a release after this is merged if possible.  Currently the Clima project mocks the equiv. Travis CI env variables.

**Comment by mortenpi** [comment]
> it would be great to tag a release after this is merged if possible.

0.26 is still some ways out, but I think we can backport this and a few other PRs and release 0.25.4 over the weekend or so.

**Comment by maleadt** [comment]
Yes, this works nicely now:
- https://buildkite.com/julialang/cuda-dot-jl/builds/133#327e6fc2-3dc5-4ec0-ba2e-05bb085092ea
- https://github.com/JuliaGPU/CUDA.jl/tree/gh-pages/dev
- https://juliagpu.github.io/CUDA.jl/dev/

**Review by MichaelHatherly — APPROVED** [review]

**Pull request merged**
