### PR TITLE
Warn on unsupported arguments in contents, index, autodocs, and meta blocks

### LINKED ISSUE #2306: Throw an error if unexpected keys are provided
I thought I stumbled over this bug https://github.com/JuliaDocs/Documenter.jl/issues/936 but what I actually missed is the initial upper case of Pages in the @contents block. 

It would be good to throw an error when unexpected or misspelled keys are provided.

`@autodocs` only accepts: `Modules`, `Filter`, `Pages`, `Private`, `Public`, `Order`. Example keys that would error: `Module`, `pages`, `DocTestSetup`
`@contents` should only accept `Pages` and `Depth`
...

### PR DESCRIPTION
**Pull request by odow**
Closes #2306

I don't know the best way to test this. I also decided to warn, rather than error, because doing so might break working builds if they have added some additional arguments in there, intentionally or otherwise.

### CODE REVIEW

**Review by mortenpi — APPROVED** [review]
This LGTM. Anything else you wanted to do here @odow or can we merge this?

**Comment by odow** [comment]
I don't have any other plans. Except I wasn't really sure how to test properly

**Comment by mortenpi** [comment]
> Except I wasn't really sure how to test properly

In principle, some `@test_logs` calls in `test/errors` should probably do it? But it would probably require reorganizing the test, so I'm happy to merge this as is.

**Comment by odow** [comment]
:+1:

**Pull request merged**
