### PR TITLE
Backports for 0.11.3: Allow for different line range formattings depending on repo type (for 0.5)

### PR DESCRIPTION
**Pull request by cbecker**
Same as https://github.com/JuliaDocs/Documenter.jl/pull/583 but for Julia v0.5 .

### CODE REVIEW

**Comment by cbecker** [comment]
Travis is red but I think it's because it's checking against julia v0.6 and julia v0.7, which is not the goal of this PR. Let me know if you have any comments, I'm eager to merge this as I'm using bitbucket and I'd like to start using Documenter on my project :)

**Comment by mortenpi** [comment]
This should target `release-0.11` I think. Julia 0.5 was dropped in Documenter 0.12, so there is no need to merge this into the 0.10 branch, right?

0.7 tests won't pass, but 0.6 and 0.5 ones should.

**Comment by cbecker** [comment]
Thanks, yes, I noticed that I was using an outdated clone. I've updated the PR, I'll close and re-open the PR to trigger CI.

**Comment by mortenpi** [comment]
The commit still looks outdated (the TLDs are still there). Probably best to simply [`cherry pick -x`](https://git-scm.com/docs/git-cherry-pick) the 860546f50bad1578e451a48437115681f84e32fc commit.

**Comment by cbecker** [comment]
Thanks, I missed that. Should be alright now.

**Pull request merged**
