### PR TITLE
Remove Compat dependency and references to Pkg.dir

### PR DESCRIPTION
**Pull request by ararslan**
Also require 0.7

The diff is big

### CODE REVIEW

**Comment by ararslan** [comment]
FYI this is needed fairly urgently to get 1.0 docs for Julia itself

**Comment by mortenpi** [comment]
Ok, this is a bit of a surprise. I somehow assumed that a 0.6-Compatted package would _just work_ on 1.0. I'll merge and tag #782, and then we can deal with this next.

**Comment by fredrikekre** [comment]
@mortenpi it's chill, I built docs locally and pushed to gh pages for now so there is no rush.

**Comment by mortenpi** [comment]
This is not actually necessary for 0.7/1.0 deployments, right? Documenter should actually be working fine on 1.0 at the moment.

`Pkg.dir` does need to be fixed, but that only affects `Travis.genkeys` and `generate`, neither of which are important for doc builds.

**Comment by mortenpi** [comment]
The deprecation that failed the deployment was [fixed in v0.19.3](https://github.com/JuliaDocs/Documenter.jl/pull/777/files#diff-2838712d7a9d8b22fbc48aecb3bf150dL533), but unfortunately Documenter hadn't been updated in Base. Ref: JuliaLang/julia#28559

**Comment by fredrikekre** [comment]
#795

**Pull request closed without merging**
