### PR TITLE
drop settings from `DCtx`

### PR DESCRIPTION
**Pull request by laborg**
PR to see if CI complains about missing setting.

### CODE REVIEW

**Comment by laborg** [comment]
I don't understand the linkcheck error. Is this a CI problem or has this something to do with this branch?

**Comment by goerz** [comment]
It's probably fine, but `DocumenterInterLinks` might touch on these internals. So, we should run the `DocumenterInterLinks` test suite before merging this, just to double-check. That's not necessarily a blocker: I'm fine adapting `DocumenterInterLinks` if any internals change, but I'd have to know.

I'll try to get around to checking this…

**Comment by goerz** [comment]
All good, as far as the plugins are concerned. I checked both `DocumenterInterLinks` and `DocumenterCitations`.

**Review by goerz — APPROVED** [review]

**Comment by mortenpi** [comment]
We should make sure that this ends up in 1.4.0, in case it does cause some breakage somewhere.

**Pull request merged**
