### PR TITLE
stop deploying to the release- folder

### PR DESCRIPTION
**Pull request by fredrikekre**
This should actually be safe since Documenter don't remove the old directories, so links should still work.

### CODE REVIEW

**Comment by mortenpi** [comment]
Code LGTM. I would leave this open for a short while to see if we gather any feedback.

You're right that this is essentially non-breaking. But I think I should nevertheless ANN the release with this change on Discourse, possibly together with a script / automated PRs that would remove the old `release-x.y` directories from packages.

**Comment by mortenpi** [comment]
Also, I was wondering that perhaps we should move the `release-x.y` ones last in `generate_version_file` in this PR? I.e. in `for group in (named_folders, release_folders, tag_folders)`. Or, I guess we could remove them altogether.. this way they will stay on the `gh-pages` branch, but will be hidden from the reader.

**Comment by fredrikekre** [comment]
Yea lets move them last. If people don't want them to show they can purge the gh-pages branch from these. Then some time in the future we can remove them from generate_version_file, since at that time Documenter has not build those branches in a while anywa.

**Comment by fredrikekre** [comment]
Actually, lets remove them from the version selector but leave the old `release-` folders on the branch. That way links will still work as you say.

**Comment by fredrikekre** [comment]
Rebased.

**Pull request merged**
