### PR TITLE
Update guide.md

### PR DESCRIPTION
**Pull request by Kunz-David**
Added setting to prettyurls, that also chcecks for Github Actions ENV.

### CODE REVIEW

**Comment by mortenpi** [comment]
I don't think this is necessary. GitHub Actions always sets `CI = true`: https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

**Comment by Kunz-David** [comment]
Ahh, I see. I just assumed that when I'm using only GitHub Actions, that using only `CI = true` (which I thought was short for `TRAVIS_CI` or something similar) wouldn't do the trick.
I thought so because of this:
>Alternatively, if your goal is to eventually set up automatic documentation deployment
   with Travis CI (see [Hosting Documentation](@ref)), you can also use their environment
   variables to determine Documenter's behavior in `make.jl` on the fly:

So maybe this should be changed to say something like:
"Alternatively, if your goal is to eventually set up automatic documentation deployment with Travis CI **or GitHub Actions** (see [Hosting Documentation](@ref)), you can also use their environment variables to determine Documenter's behavior in `make.jl` on the fly:"

What do you think? @mortenpi

**Comment by mortenpi** [comment]
That sounds reasonable to me. If you'd like to update the PR with that change, I'd be happy to merge it.

**Comment by Kunz-David** [comment]
OK, nice :)
Here is the [PR](https://github.com/JuliaDocs/Documenter.jl/pull/1316).

**Pull request closed without merging**
