### PR TITLE
Escape single paranthesis

### PR DESCRIPTION
**Pull request by aaruni96**
This stops a single parenthesis from crashing search. A second one will still crash it, but I don't know enough javascript to handle that cleanly.

### CODE REVIEW

**Comment by mortenpi** [comment]
cc @LilithHafner or @Hetarth02: any thoughts here by any chance?

**Comment by LilithHafner** [comment]
Ever since switching to the new search the search pane sometimes doesn't show up for me. It's flaky enough that it is inconvenient for me to debug other search-related issues.

**Comment by mortenpi** [comment]
> search pane sometimes doesn't show up for me.

FWIW, I'm pretty sure that got fixed in #2458.

**Comment by fingolfin** [comment]
All in all, isn't this a clear improvements with no downsides?

Can at least the workflows be run?

**Comment by Hetarth02** [comment]
Since we are doing this, we should also see if there are any other characters which break it like this.

**Comment by aaruni96** [comment]
> break it like this

Maybe a `/`, and `[` ?

The unescaped parenthesis is directly plugged into the regx engine, and the regx then suddenly has a wrong grouping causing the engine to crash.

AFAIK, regx only uses so many special characters in its patterns: `/` to separate, `(`, `)` to make groups, and `[`, `]` to make sets, but there could be one or two more.

**Comment by fingolfin** [comment]
Depending on which type of regex, there can be many more special character, including `.` `*` `|` -- see https://www.w3schools.com/jsref/jsref_obj_regexp.asp for a more comprehensive overview relevant to JavaScript.

**Comment by fingolfin** [comment]
Relevant SO post: https://codereview.stackexchange.com/questions/153691/escape-user-input-for-use-in-js-regex

**Comment by mortenpi** [comment]
And SO points to MDN and to an ECMAScript proposal:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#escaping
* https://github.com/tc39/proposal-regex-escaping

Let's just implement the MDN suggestion. It looks straightforward.

**Comment by fingolfin** [comment]
Can someone please let the CI tests run? @aaruni96 pushed an update using the discussed MDN regex, so hopefully it now covers more (all?) cases.

Also if it passes and y'all are happy, I hope it can merged soon :-)

**Comment by Hetarth02** [comment]
CC @mortenpi

**Comment by LilithHafner** [comment]
FWIW, I prefer allowing checks to run without approval, even from first time contributors.

**Review by mortenpi — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
