### PR TITLE
fix some deprecations

### PR DESCRIPTION
**Pull request by fredrikekre**
Building the docs on CI results in a huge amount of depwarn again, fixed most of them.

Needs https://github.com/JuliaLang/Compat.jl/pull/452 to pass on julia 0.6

It would be nice with a new release with this and 611aa82bfac3ea64306a5b8e8be9675cbc519eb8 which should silence most of the warnings.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Tests pass now, but there was a newer nightly on macOS, which also included some recent `find*` changes, should be fixed with https://github.com/JuliaLang/Compat.jl/pull/457 so we could either wait for that or merge this and fix that in a separate PR.

**Comment by JeffBezanson** [comment]
Thanks for this! I suspect these deprecations are slowing down the doc build in julia CI quite a bit, so would be good to get this released as soon as possible.

**Comment by KristofferC** [comment]
Looks like DocStringExtensions need to be fixed as well? 

```
Stacktrace:
 [1] <(::Int64, ::Nothing) at ./operators.jl:227
 [2] >(::Nothing, ::Int64) at ./operators.jl:250
 [3] keywords(::Function, ::Method) at /home/travis/.julia/v0.7/DocStringExtensions/src/utilities.jl:252
.
.
```

on Travis

**Comment by fredrikekre** [comment]
Yes, I am waiting for https://github.com/JuliaLang/Compat.jl/pull/457 for that

**Comment by KristofferC** [comment]
Ah, of course. Sorry.

**Comment by Keno** [comment]
Can we just take the most direct route possible to getting rid of the deprecations, even if that means an ugly hack here? All the deprecation warnings are causing Base CI to time out.

**Comment by JeffBezanson** [comment]
Seconded. This is now top priority, as it is slowing down Base development quite a bit. In many cases CI times out because of it.

**Comment by mortenpi** [comment]
The nightly test should pass now. Once it does, I'll merge and tag.

**Comment by KristofferC** [comment]
Ok, this passed on 0.6 and nightly (linux)

**Pull request merged**
