### PR TITLE
[tex] Adjusting the TOC style

### PR DESCRIPTION
**Pull request by inkydragon**
xref: JuliaLang/julia#43698

1. Use compact line spacing in TOC: `\cftbeforepartskip`, `\cftbeforechapterskip`
2. Increase the spacing between chapter numbers and chapter names: `\cftchapternumwidth`
3. Increase indent before section number: `\cftsectionindent`

image

output: [DocumenterLaTeX-toc#1750.pdf](https://drive.google.com/file/d/1-BRhgatXAjw9EAze45jRWrcSVaBPlbF8/view?usp=sharing) v.s. [DocumenterLaTeX-master+7beb208b3.pdf](https://drive.google.com/file/d/1JzP55M8XSPg-58BTXxcLWJjIqCE7zhL8/view?usp=sharing)

### CODE REVIEW

**Comment by inkydragon** [comment]
This pr does not modify the display depth in the TOC (`\settocdepth`).

And with only the chapter names (`\settocdepth{chapter}`):
image

[DocumenterLaTeX-chapter-only.pdf](https://drive.google.com/file/d/1lEIED398E-MoL_SVwjIxItlJDn4o3tvP/view?usp=sharing)

**Comment by ViralBShah** [comment]
Any idea about the failing test? Maybe rebase?

@fredrikekre Is merging this what we broadly need for the pdf of the julia manual to look nicer, and is this the right place (as opposed to the julia repo PR linked above)?

**Comment by ViralBShah** [comment]
@inkydragon Can you look into the failing test? It looks relevant.

**Comment by fredrikekre** [comment]
Looks good, I don't think the failure is related, I can look at it tomorrow.

Can you add a note in the changelog?

**Comment by ViralBShah** [comment]
Bump.

**Comment by fredrikekre** [comment]
Tests should be fixed by 33c53bd43657dbbd26532b35646d842526a86ff8.

**Comment by ViralBShah** [comment]
We still have spacing issues - however I think that the PDF should only have TOC depth at chapter level (and not section level)

Screen Shot 2022-04-03 at 11 03 36 AM

**Pull request merged**
