### PR TITLE
Better error message for failing to evaluate setup code, fix #785.

### LINKED ISSUE #785: Improve error on DocTestSetup failure
Give some context if a `DocTestSetup` in an at-meta block fails. The current stacktrace is not that helpful:

```
ERROR: LoadError: LoadError: UndefVarError: srand not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] eval(::Module, ::Any) at ./boot.jl:319
 [3] doctest(::Markdown.Code, ::Dict{Symbol,Any}, ::Documenter.Documents.Document, ::Documenter.Documents.Page) at /home/travis/build/JuliaDocs/Documenter.jl/src/DocChecks.jl:182
```

### PR DESCRIPTION
**Pull request by fredrikekre**
```
┌ Warning: Error evaluating expression from doctest setup, ignoring.
│   expr = :(a = srand())
└ @ Documenter.DocChecks ~/.julia/dev/Documenter/src/DocChecks.jl:185
```

### CODE REVIEW

**Comment by mortenpi** [comment]
Should we ignore it though?

**Comment by fredrikekre** [comment]
Now gives
```
┌ Error: Error evaluating expression from doctest setup
│   expr = :(srand(1))
│   exception = UndefVarError: srand not defined
└ @ Documenter.DocTests ~/dev/Documenter/src/DocTests.jl:108
```

**Comment by KristofferC** [comment]
But it still won't throw?

**Comment by fredrikekre** [comment]
It skips that doctest. Same as we do for other errors we encounter.

**Comment by mortenpi** [comment]
It doesn't fail doctesting right now though, right?

**Comment by fredrikekre** [comment]
Hmm, so should we ` push!(doc.internal.errors, :doctest)` there as well?

**Pull request merged**
