### PR TITLE
Allow whitelisting links in linkcheck

### LINKED ISSUE #447: Need a way of whitelisting certain url's in linkcheck
This was a feature sphinx had that we need in one or two places in base to get linkcheck to pass. There's a url on the kde bug tracker that always returns errors when you try to access it from the particular machine I do release preparation and testing on.

### PR DESCRIPTION
**Pull request by mortenpi**
@tkelman apologies for being a bit passive on the Documenter front at the moment. I assumed this to be a "nice to have".

I think adding another keyword argument would do the trick. This more or less copies how this is done in Sphinx as far as I can tell.

This will require a minor version bump, so I am thinking it might be time to merge a couple of the other PRs as well while we're at it. How fast would you like to have this available?

Fixes #447.

### CODE REVIEW

**Comment by tkelman** [comment]
Cool, this looks like it'll do, thanks much. If you can get out a new release in a week or so, it can be part of rc2 instead of rc1 if needed.

**Comment by mortenpi** [comment]
If I'd say I'll do a release by Friday, would that be fast enough for rc1?

**Comment by tkelman** [comment]
rc1 will probably be before next friday, but doesn't absolutely need this to be available yet

**Comment by tkelman** [comment]
Maybe that was ambitious. If someone hadn't broken the build on power, we'd probably have rc1 already.

Anyway, put to good use in https://github.com/JuliaLang/julia/pull/21473/commits/0afcf0539b9159896397e8e4050ae03eff5ed770.

**Pull request merged**
