### PR TITLE
Add User and IdentitesOnly lines to the generated SSH config

### PR DESCRIPTION
**Pull request by fjarri**
I am trying to set up documentation generation on CircleCI, and it seems that these entries are required for the `git push` to work, otherwise I get an error about the key not having write privileges (in fact, as I can see from the last access info on GitHub, it wasn't even used).

I am not sure what is the difference between Circle and Travis (where these entries are not required), so it would be great if someone more knowledgeable took a look at it, so that this PR doesn't break anything.

### CODE REVIEW

**Comment by mortenpi** [comment]
This should have no effect when running on Travis, so LGTM. Thanks, @fjarri!

**Comment by mortenpi** [comment]
> I am trying to set up documentation generation on CircleCI, and it seems that these entries are required for the `git push` to work, otherwise I get an error about the key not having write privileges (in fact, as I can see from the last access info on GitHub, it wasn't even used).

I wonder if CircleCI has a default SSH key generated that gets precedence of ours?

**Comment by fjarri** [comment]
It does have a read-only key it uses to check out the repo, so maybe that's the reason. Travis seems to only have a single read/write key, judging by "Deploy Keys" settings tab in my projects. I can't change the access preferences now, and I don't remember if I could select them when I connected CircleCI.

**Comment by mortenpi** [comment]
> It does have a read-only key it uses to check out the repo, so maybe that's the reason.

That's probably it then. SSH manages to log in with that one, so it never gets around to trying the write key.

**Pull request merged**
