### PR TITLE
Fix the `deploy_folder` fallbacks and the docstring for `deploy_folder`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@mortenpi @fredrikekre I think this should fix the `deploy_docs` stuff and the docstrings that Fredrik mentioned.

**Comment by DilumAluthge** [comment]
I tried to add a docstring for `DeployDecision`. But this broke LinkCheck. When I removed the docstring for `DeployDecision`, then LinkCheck passed.

**Comment by mortenpi** [comment]
I re-added the docstring, let's see what happens. I don't see anything in it that should cause linkcheck to fail. However, Travis and AppVeyor tests were both failing too, without the docstring.

**Comment by DilumAluthge** [comment]
All right I think I should've fixed the test now.

**Comment by DilumAluthge** [comment]
Okay, CI is passing now.

**Comment by DilumAluthge** [comment]
@mortenpi @fredrikekre Anything else I should add to this PR?

**Pull request merged**
